imrt_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50

left_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

right_wheel_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
